"""empty message

Revision ID: 2fd3dacefd9d
Revises: 6fb3dd4a92ab
Create Date: 2020-08-03 14:18:24.250226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd3dacefd9d'
down_revision = '6fb3dd4a92ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'id')
    # ### end Alembic commands ###
