"""empty message

Revision ID: 31feb82a9019
Revises: 
Create Date: 2020-08-03 05:26:35.716024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31feb82a9019'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('personal_email_address', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'recruits', ['personal_email_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruits', type_='unique')
    op.drop_column('recruits', 'personal_email_address')
    # ### end Alembic commands ###
