"""empty message

Revision ID: 3df3c81aca57
Revises: 
Create Date: 2020-08-02 23:10:28.174144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df3c81aca57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('personal_email_address', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'recruits', ['personal_email_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruits', type_='unique')
    op.drop_column('recruits', 'personal_email_address')
    # ### end Alembic commands ###
