"""empty message

Revision ID: 6a3aac8b481f
Revises: 01e00bc3711d
Create Date: 2020-08-03 13:54:59.049921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3aac8b481f'
down_revision = '01e00bc3711d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('chatname', sa.String(length=100), nullable=True))
    op.add_column('recruits', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('recruits', 'rocketchat_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('rocketchat_user', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recruits', 'id')
    op.drop_column('recruits', 'chatname')
    # ### end Alembic commands ###
