"""empty message

Revision ID: 6fb3dd4a92ab
Revises: 6a3aac8b481f
Create Date: 2020-08-03 14:00:53.451961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb3dd4a92ab'
down_revision = '6a3aac8b481f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'id')
    # ### end Alembic commands ###
