"""empty message

Revision ID: 8a0929a6fa45
Revises: e6c44e233f89
Create Date: 2020-08-03 13:12:53.125736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0929a6fa45'
down_revision = 'e6c44e233f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('chatname', sa.String(length=100), nullable=True))
    op.drop_column('recruits', 'rocketchat_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('rocketchat_user', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recruits', 'chatname')
    # ### end Alembic commands ###
