"""empty message

Revision ID: b021599bfe54
Revises: 2a42400b31f0
Create Date: 2020-08-03 13:27:38.976100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b021599bfe54'
down_revision = '2a42400b31f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('rocketchat_user', sa.String(length=100), nullable=True))
    op.drop_column('recruits', 'chatname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('chatname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recruits', 'rocketchat_user')
    # ### end Alembic commands ###
