"""empty message

Revision ID: b29286d67068
Revises: 31feb82a9019
Create Date: 2020-08-03 05:39:22.594036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29286d67068'
down_revision = '31feb82a9019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'chort')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('chort', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
