"""empty message

Revision ID: e6c44e233f89
Revises: 872b83cb867e
Create Date: 2020-08-03 06:32:20.166832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c44e233f89'
down_revision = '872b83cb867e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('cohort', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'cohort')
    # ### end Alembic commands ###
